# Use the arm64 version of a stable Nginx image for Apple Silicon compatibility
FROM --platform=linux/arm64 nginx:1.19-alpine

# Overwrite the default server configuration with our own compatible version.
COPY default.conf /etc/nginx/conf.d/default.conf

# Copy the web content.
COPY index.html /usr/share/nginx/html/index.html