# Use the official Nginx image from Docker Hub
FROM nginx:1.20-alpine

# Set the working directory
WORKDIR /usr/share/nginx/html

# Remove the default Nginx welcome page
RUN rm -f index.html

# Copy our custom index.html file to the container
COPY index.html .